### ISSUE TITLE
Feature request: addAll() ?

### ISSUE THREAD

**Issue by zilveer** [silviodelgado/RouterJS#1]
Hi,
first of all I would like to thank you for such a super simple and lightweight for javascript routing, thanks!

I would like to know if there is any possibility for you to add a function similiar to `add()` but instead it should apply for all pages.
This would be awesome if you could, if not perhaps you can help me and guide me of how I can achieve this?

Once again thanks for such a great plugin!
best regards, Zilveer

**Comment by silviodelgado** [comment]
> 

Can you tell more about your needs?

**Comment by zilveer** [comment]
basically, I would like to have a simple function called for example `addAll`, that function should apply for all routes, so it will be called first before anything else for all routes.

For example:

```Router
  .add(/about/, show_about)
  .add(/number:([0-9]+)/, show_number)
  .apply()
  .addAll(/(perhaps * or apply for specific routes? )/, function(data) {   ////some coding either for * (all routes) or by specifying routes?
     //some coding
        })
  .start();```

**Comment by silviodelgado** [comment]
@zilveer 
As you can use regex into `.add()` method, you also can define a regex which will capture all pages you want to execute the same method. ;-)

**Comment by zilveer** [comment]
@silviodelgado can u please clarify with an example.

I want every route to call the function `forAllRoutes(data)` as well as I want every route to have their own  function.
```  .add(/about/, show_about)
  .add(/number:([0-9]+)/, show_number)
  .add(/(what regex should I add here to apply it for all routes above also? )/, function(data) {   ////some coding  for * (all routes)
  
forAllRoutes(data);                //this should be called for every single route above.
        })
  .apply()
  .start();```

**Comment by silviodelgado** [comment]
@zilveer Now I understand.
I'll think about it and how I can solve your need.

**Comment by silviodelgado** [comment]
@zilveer It's ready!

Two new methods were added:
- beforeAll(handler) (to be executed before any specific route method)
- afterAll(handler) (to be executed after any specific route method)

**Comment by zilveer** [comment]
@silviodelgado 
Damn you were fast :)

Thank you for this! 👍

**Comment by silviodelgado** [comment]
@zilveer You're welcome!

**Comment by zilveer** [comment]
@silviodelgado 
One last wish,  is it possible to make beforeAll and afterAll more powerful by excluding some routes,  either by regex or something else ?

That would make it so much more powerful.

And once again thanks for this simple tiny router javascript plugin which I literally haven't seen somewhere else.

Regards Zilveer

**Comment by silviodelgado** [comment]
@zilveer If yes, it will be called beforeAllBut (or afterAllBut). lol 

Seriously, if so many functions are added to the code, it will lose its simplicity.
But, I'll think about it anyway. ;-)

**Comment by zilveer** [comment]
@silviodelgado 
It will still be tiny and lightweight but so damn powerful!
I think you can sort it out in a good way :)

I would call RouterJS literally the most powerful vanillajs router plugin. There is nothing better with its size.
All other routers are at least 5-10x of the size and cannot accomplish what u have created .

Great work!

Regards Zilveer

**Comment by zilveer** [comment]
@silviodelgado any news regarding beforeAllBut and afterAllBut?
